## Nympy Properties

In [9]:
import numpy as np

ar=np.array([[1,2,3],
              [2,3,4]],dtype=np.int)

print(ar,'\n')
print('Properties of "ar"','-'*25,'\n')
print('Number of dim:',ar.ndim)
print('Shape:',ar.shape)
print('Size:',ar.size)
print('Data Type:',ar.dtype)
print('Object Type:',type(ar))

[[1 2 3]
 [2 3 4]] 

Properties of "ar" ------------------------- 

Number of dim: 2
Shape: (2, 3)
Size: 6
Data Type: int32
Object Type: <class 'numpy.ndarray'>


In [15]:
ar0=np.zeros((3,4))
print(ar0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# 比較一下
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
ar1=np.ones((3,4))
print(ar1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 有沒有 np.sevens ???

## basic array generating
### np.arange()
### np.linspace()
### array.reshape()

In [17]:
arg=np.arange(10,20,2) # start,end,step
print(arg)

[10 12 14 16 18]


#### 檢查一下 arg 的 type
#### 仔細看看，與 list 有什麼不同 ?

In [20]:
asp=np.arange(12).reshape((3,4))
print(asp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
a=np.linspace(1,10,20) # start,end,sections
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [22]:
a=a.reshape(4,5)
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


### math operation

In [25]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(b)
print(a-b)
print(a+b)
print(a*b)
print(b**2)

[0 1 2 3]
[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[        inf 20.         15.         13.33333333]
[0 1 4 9]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


#### How about a/b ?

In [27]:
print(b!=0)

[False  True  True  True]


## matrix operation

In [29]:
a=np.array([[1,3,5],
           [2,4,6]])
b=np.arange(6).reshape(2,3)
c=np.arange(6).reshape(3,2)
print(a)
print(b)
print(c)


[[1 3 5]
 [2 4 6]]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


### X * Y, np.dot(X,Y), and X.dot(Y)

In [19]:
print(a*b) # same shape

[[ 0  3 10]
 [ 6 16 30]]


In [ ]:
np.dot(a,b) # opps, an error!

In [12]:
np.dot(a,c) # shape: [x,y]dot[y,z] get [x,z] matrix
print(d)

[[26 35]
 [32 44]]


numpy.ndarray

In [6]:
d=a.dot(c)
print(d)
type(d)

[[26 35]
 [32 44]]


numpy.ndarray

### 向量 Vector 乘法

In [31]:
ar1=np.array([3,5,7,9])
ar2=np.array([1,2,3,4])
print(ar1,'\n',ar2)
print('\n',ar1*ar2)
print(np.dot(ar1,ar2))

[3 5 7 9] 
 [1 2 3 4]

 [ 3 10 21 36]
70


In [32]:
ar3=np.array([[1],[2],[3],[4]])
print('\n-----------------------------Vectors')
print(f'ar1=\n{ar1}\nar2=\n{ar2}\nar3=\n{ar3}')
print('\n---------------------------Vectors *')
print(f'ar1*ar2=\n{ar1*ar2}')
print(f'ar1*ar3=\n{ar1*ar3}')
print('\n-------------------------Vectors dot')
print(f'dot (ar1,ar2)=\n{np.dot(ar1,ar2)}') # number
print(f'dot (ar1,ar3)=\n{np.dot(ar1,ar3)}') # list


-----------------------------Vectors
ar1=
[3 5 7 9]
ar2=
[1 2 3 4]
ar3=
[[1]
 [2]
 [3]
 [4]]

---------------------------Vectors *
ar1*ar2=
[ 3 10 21 36]
ar1*ar3=
[[ 3  5  7  9]
 [ 6 10 14 18]
 [ 9 15 21 27]
 [12 20 28 36]]

-------------------------Vectors dot
dot (ar1,ar2)=
70
dot (ar1,ar3)=
[70]


### evaluation in row or in column

#### np.random.matrix
#### sum()、max()、min()、mean()、median()
#### axis=1 -> compare columns; axis=0 -> compare rows
#### argmin()、argmax()
#### cumsum()、diff()
#### nonzero()
#### sort()、transppose()、clip()

In [31]:
a=np.random.random((2,4))
print(a)

[[0.25793421 0.5138923  0.1296704  0.27761434]
 [0.77569067 0.86149936 0.21723639 0.67246363]]


In [32]:
print(np.sum(a))

3.7060013059221655


In [35]:
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))

0.8614993561545388
0.1296704038901968
3.7060013059221655
0.4632501632402707
0.39575331902941296


In [37]:
print(np.min(a,axis=1)) # minumum in columns elements
print(np.min(a,axis=0)) # Minumum in rows e.ements

[0.1296704  0.21723639]
[0.25793421 0.5138923  0.1296704  0.27761434]


In [43]:
d=np.array([[2,8,5],
            [7,1,6]])
print(np.max(d,axis=1)) # maxium in columns elements
print(np.max(d,axis=0)) # Maxium in rows elements

[8 7]
[7 8 6]


In [33]:
A=np.arange(2,14).reshape((3,4)) # why arrange, two brackets for reshape, np.command.command
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [34]:
print(np.argmin(A,axis=0)) # return index,not the element
print(np.argmax(A))

[0 0 0 0]
11


In [30]:
print(np.mean(A))
print(A.mean())
print(np.mean(A,axis=1)) # means for every elements in each columns

7.5
7.5
[ 3.5  7.5 11.5]


In [56]:
print(np.median(A,axis=1))

[ 3.5  7.5 11.5]


#### np.cumsum 累加，含首項，axis 無預設值，未設定則為全排序

In [36]:
A=np.array([[1,2,0,4],[5,0,7,8],[0,10,11,12]])
print(A)
print(np.cumsum(A))
print(np.cumsum(A,axis=1))
print(np.cumsum(A,axis=0))

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]
[ 1  3  3  7 12 12 19 27 27 37 48 60]
[[ 1  3  3  7]
 [ 5  5 12 20]
 [ 0 10 21 33]]
[[ 1  2  0  4]
 [ 6  2  7 12]
 [ 6 12 18 24]]


#### np.diff 與前項差額，首項不計。axis 預設值為 1

In [37]:
print(A)
print(np.diff(A))
print(np.diff(A,axis=0))
print(np.diff(A,axis=1)) 

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]
[[ 1 -2  4]
 [-5  7  1]
 [10  1  1]]
[[ 4 -2  7  4]
 [-5 10  4  4]]
[[ 1 -2  4]
 [-5  7  1]
 [10  1  1]]


#### np.npnzero() is a tricky function, for programmer use
#### 奇怪的表達方式，矩陣有 12 項，回傳結果只有 9 項?

In [54]:
print(A)
nzA=np.nonzero(A)
print(nzA)

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]
(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 3, 0, 2, 3, 1, 2, 3], dtype=int64))


#### 這樣就看出來了
#### 原來是非 0 項的列、行位置配對

In [55]:
p1=nzA[0]
p2=nzA[1]
p=np.array([p1,p2])
print(p)

[[0 0 0 1 1 1 2 2 2]
 [0 1 3 0 2 3 1 2 3]]


In [58]:
print(A)
print(np.sort(A)) # default: axis=1
print(np.sort(A,axis=0))

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]
[[ 0  1  2  4]
 [ 0  5  7  8]
 [ 0 10 11 12]]
[[ 0  0  0  4]
 [ 1  2  7  8]
 [ 5 10 11 12]]


In [59]:
print(A)
print(np.transpose(A))
print((A.T)) # same as above

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]
[[ 1  5  0]
 [ 2  0 10]
 [ 0  7 11]
 [ 4  8 12]]
[[ 1  5  0]
 [ 2  0 10]
 [ 0  7 11]
 [ 4  8 12]]


In [60]:
print(A)
print(np.clip(A,3,7)) # set the lowwer and upper limitation

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]
[[3 3 3 4]
 [5 3 7 7]
 [3 7 7 7]]


#### 又一個比較難理解的功能
#### 類似遮罩，或是篩子的概念
#### 將原始矩陣中，超出設定範圍的元素，以設定範圍的極限值取代
#### 設定範圍內的元素，保留原值

### Index

In [41]:
A=np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [42]:
print(A[3])

6


In [43]:
A=A.reshape(3,4)
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [44]:
print(A[2,3])
print(A[2][3])

14
14


In [45]:
print(A[2]) # row 2 only
print(A[:2]) # row first to row 2
print(A[1:]) # row one to the last row

[11 12 13 14]
[[ 3  4  5  6]
 [ 7  8  9 10]]
[[ 7  8  9 10]
 [11 12 13 14]]


In [46]:
print(A[:,2]) # column 2
print(A[:,:2]) # column first to column 2
print(A[:,2:]) # column 2 to the last column

[ 5  9 13]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 5  6]
 [ 9 10]
 [13 14]]


In [47]:
print(A[:,[1,3]]) # column 1 and 3

[[ 4  6]
 [ 8 10]
 [12 14]]


 ## Matrix Loop
 ### for loop

In [48]:
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [49]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [50]:
for column in A:
    print(column) # same as row iteration ????

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


#### 原來，numpy 矩陣不能迭代 column
#### 變通之道，將矩陣轉置後再行迭代

In [63]:
for column in A.T:
    print(column)

[1 5 0]
[ 2  0 10]
[ 0  7 11]
[ 4  8 12]


In [64]:
print(A)
print(A.flat) # generate a iterator

[[ 1  2  0  4]
 [ 5  0  7  8]
 [ 0 10 11 12]]


In [65]:
print(list(A.flat)) # list a iterator
print(A.flatten()) # a nympy array

[1, 2, 0, 4, 5, 0, 7, 8, 0, 10, 11, 12]
[ 1  2  0  4  5  0  7  8  0 10 11 12]


In [66]:
for item in A.flat:
    print(item)

1
2
0
4
5
0
7
8
0
10
11
12


### merge arrays
#### vstack ( )、hstack( )
#### np.newaxis
#### np.concatenate( )

In [51]:
A=np.array([1,1,1])
B=np.array([2,2,2])
V=np.vstack((A,B))
print(V)

[[1 1 1]
 [2 2 2]]


In [145]:
print(A.shape,V.shape)

(3,) (2, 3)


In [146]:
H=np.hstack((A,B))
print(H)

[1 1 1 2 2 2]


In [125]:
print(H.shape)

(6,)


#### 單維向量轉置後，仍為向量

In [126]:
print(A.T) # Vector is always a vector, no matter vertical or horizontal

[1 1 1]


In [147]:
print(A)

[1 1 1]


In [130]:
print(A[np.newaxis,:])

[[1 1 1]]


In [68]:
print(A[:,np.newaxis])

[[1]
 [1]
 [1]]


In [69]:
print(A)

[1 1 1]


In [74]:
C=np.array([[1,1,1]]) #1'st square brackets mean array,second pairs mean dimension (row or column)
print(C)

[[1 1 1]]


In [75]:
print(A.shape) # vector
print(B.shape) # vector
print(C.shape) # matrix

(3,)
(3,)
(1, 3)


### split arrays
#### np.split( )

In [56]:
A=np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
print(np.split(A,2,axis=1))
# 將欄值拆分為 2 組

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [58]:
print(np.split(A,3,axis=0))
# 將列值拆分為 3 組

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [83]:
print(np.array_split(A,3,axis=1)) # unequal split

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [178]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [181]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### two types of copy

In [189]:
A=np.arange(4)
print(A)

[0 1 2 3]


In [190]:
B=A
C=A.copy() # deep copy

In [191]:
print(B)
print(C)

[0 1 2 3]
[0 1 2 3]


In [192]:
A[0]=5
print(A)

[5 1 2 3]


In [193]:
print(B)
print(C)

[5 1 2 3]
[0 1 2 3]


In [208]:
B is A

True

In [209]:
C is A

False