In [29]:
import numpy as np

ar=np.array([[1,2,3],[2,3,4]],dtype=np.int)

print(ar,'\n')
print('Properties of "ar"','-'*25,'\n')
print('Number of dim:',ar.ndim)
print('Shape:',ar.shape)
print('Size:',ar.size)
print('Data Type:',ar.dtype)
print('Object Type:',type(ar))
ar0=np.zeros((3,4))
print(ar0+2)
ar1=np.ones((3,4))
print(ar1*7)
np.arange(10,20,2) # start,end,step
asp=np.arange(12).reshape((3,4))
print(asp)
a=np.linspace(1,10,20) # start,end,sections
print(a)
a=a.reshape(4,5)
print(a)

[[1 2 3]
 [2 3 4]] 

Properties of "ar" ------------------------- 

Number of dim: 2
Shape: (2, 3)
Size: 6
Data Type: int32
Object Type: <class 'numpy.ndarray'>
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]
